### PR TITLE
Hide VI indicator with env var

### PR DESCRIPTION
**Pull request by OlivierCuyp**
Hi Dave,

I'm not using the VI mode at all, so this PR is based on some assumptions.
It works fine for my usage since I wanted to keep it as compact as possible.
It might not please everyone, but who knows.

### CODE REVIEW

**Comment by daveyarwood** [comment]
Hi, thanks for the PR!

I think for those of us who use vi mode, it would look weird for the vi mode indicator to disappear each time we go into normal mode.

I like the intent of this PR, though. I wonder if there is a better way for us to determine when you want to use vi mode, and show the indicator only when that's the case?

One thing I can think of is to set a global variable called something like `tomita_vi_mode_on` in your fish.config. Then in the prompt logic, if that variable has a non-zero value (e.g. `yes`, `true`, technically anything will work), then we would show the prompt, otherwise we would hide it by default.

**Comment by OlivierCuyp** [comment]
@daveyarwood couldn't we set an env var called `TOMITA_VI`or even `TOMITA_VI_MODE` as you prefer? So we don't need to edit the script itself to change the global variable.
By default we can leave it at `true`.
What do you think ?

**Comment by OlivierCuyp** [comment]
@daveyarwood I made the changes to use an env var. Tell me if you like it better this way.

**Comment by daveyarwood** [comment]
I like it -- will merge. Thanks a lot!

**Pull request merged**
